global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pp-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pp-gateway:8080']

  - job_name: 'pp-room-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pp-room-service:8081']

  - job_name: 'pp-vote-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pp-vote-service:8082']

  - job_name: 'pp-audit-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pp-audit-service:8083']
